import { SysMenuType } from '@/apps/admin/database'
import { StatusEnum } from '@/common/interfaces'
import type { AdminMenuDefinition } from './admin-menu.types'

const enabled = StatusEnum.ENABLED
const disabled = StatusEnum.DISABLED

interface BusinessPageDefinition {
  actions: ReadonlyArray<readonly [action: string, name: string]>
  icon: string
  key: string
  name: string
  path: string
  permission: string
}

const businessPages: BusinessPageDefinition[] = [
  {
    key: 'tenants',
    name: '所属单位',
    path: '/business/tenants',
    permission: 'agency:tenant',
    icon: 'lucide:building-2',
    actions: [
      ['read', '查询'],
      ['create', '新增'],
      ['update', '修改状态'],
    ],
  },
  {
    key: 'merchants',
    name: '商家账号',
    path: '/business/merchants',
    permission: 'merchant:account',
    icon: 'lucide:store',
    actions: [
      ['read', '查询'],
      ['create', '新增'],
      ['update', '编辑与启停'],
      ['delete', '删除'],
      ['credential', '配置平台凭据'],
      ['test', '连接测试'],
    ],
  },
  {
    key: 'merchantOrders',
    name: '商家订单',
    path: '/business/merchant-orders',
    permission: 'merchant:order',
    icon: 'lucide:shopping-receipt',
    actions: [
      ['read', '查询'],
      ['sync', '同步'],
      ['pay', '创建支付'],
      ['confirm_paid', '补偿确认'],
      ['cancel', '作废'],
    ],
  },
  {
    key: 'paymentAccounts',
    name: '支付账号',
    path: '/business/payment-accounts',
    permission: 'payment:account',
    icon: 'lucide:wallet-cards',
    actions: [
      ['read', '查询'],
      ['create', '新增'],
      ['bind', '配置通道与方案'],
    ],
  },
  {
    key: 'paymentOrders',
    name: '支付订单',
    path: '/business/payment-orders',
    permission: 'payment:order',
    icon: 'lucide:receipt-text',
    actions: [
      ['read', '查询'],
      ['create', '新增'],
      ['retry', '重新匹配或回查'],
    ],
  },
  {
    key: 'paymentBatches',
    name: '支付批次',
    path: '/business/payment-batches',
    permission: 'payment:batch',
    icon: 'lucide:layers-3',
    actions: [
      ['read', '查询'],
      ['create', '创建'],
      ['submit', '提交'],
      ['retry', '回查'],
    ],
  },
]

export const DEFAULT_ADMIN_MENUS: AdminMenuDefinition[] = [
  {
    key: 'dashboard',
    type: SysMenuType.FOLDER,
    name: '概览',
    path: '/dashboard',
    permission: 'dashboard',
    icon: 'ant-design:menu-outlined',
    orderNo: 1000,
    keepAlive: enabled,
  },
  {
    key: 'dashboard.workspace',
    type: SysMenuType.MENU,
    parentKey: 'dashboard',
    name: '工作台',
    path: '/workspace',
    component: '/dashboard/workspace',
    permission: 'dashboard:workspace',
    icon: 'lucide:layout-dashboard',
    orderNo: 10,
    keepAlive: enabled,
  },
  {
    key: 'business',
    type: SysMenuType.FOLDER,
    name: '业务运营',
    path: '/business',
    permission: 'business',
    icon: 'lucide:briefcase-business',
    orderNo: 995,
    keepAlive: disabled,
  },
  ...businessPages.map(({ icon, key, name, path, permission }, index) => ({
    key: `business.${key}`,
    type: SysMenuType.MENU,
    parentKey: 'business',
    name,
    path,
    component: path,
    permission,
    icon,
    orderNo: 60 - index * 10,
  })),
  ...businessPages.flatMap(({ actions, key, permission }) =>
    actions.map(([action, name]) => ({
      key: `business.${key}.${action}`,
      type: SysMenuType.PERMISSION,
      parentKey: `business.${key}`,
      name,
      permission: `${permission}:${action}`,
    })),
  ),
  {
    key: 'system',
    type: SysMenuType.FOLDER,
    name: '系统管理',
    path: '/system',
    permission: 'system',
    icon: 'ant-design:setting-outlined',
    orderNo: 990,
    keepAlive: disabled,
  },
  {
    key: 'system.user',
    type: SysMenuType.MENU,
    parentKey: 'system',
    name: '用户管理',
    path: '/system/user',
    component: '/system/user',
    permission: 'system:user',
    icon: 'ant-design:user-outlined',
    orderNo: 40,
  },
  {
    key: 'system.user.create',
    type: SysMenuType.PERMISSION,
    parentKey: 'system.user',
    name: '用户管理-新增',
    permission: 'system:user:create',
  },
  {
    key: 'system.user.delete',
    type: SysMenuType.PERMISSION,
    parentKey: 'system.user',
    name: '用户管理-删除',
    permission: 'system:user:delete',
  },
  {
    key: 'system.user.update',
    type: SysMenuType.PERMISSION,
    parentKey: 'system.user',
    name: '用户管理-更新',
    permission: 'system:user:update',
  },
  {
    key: 'system.user.read',
    type: SysMenuType.PERMISSION,
    parentKey: 'system.user',
    name: '用户管理-查询',
    permission: 'system:user:read',
  },
  {
    key: 'system.role',
    type: SysMenuType.MENU,
    parentKey: 'system',
    name: '角色管理',
    path: '/system/role',
    component: '/system/role',
    permission: 'system:role',
    icon: 'ant-design:user-switch-outlined',
    orderNo: 30,
  },
  {
    key: 'system.role.create',
    type: SysMenuType.PERMISSION,
    parentKey: 'system.role',
    name: '角色管理-新增',
    permission: 'system:role:create',
  },
  {
    key: 'system.role.delete',
    type: SysMenuType.PERMISSION,
    parentKey: 'system.role',
    name: '角色管理-删除',
    permission: 'system:role:delete',
  },
  {
    key: 'system.role.update',
    type: SysMenuType.PERMISSION,
    parentKey: 'system.role',
    name: '角色管理-修改',
    permission: 'system:role:update',
  },
  {
    key: 'system.role.read',
    type: SysMenuType.PERMISSION,
    parentKey: 'system.role',
    name: '角色管理-查询',
    permission: 'system:role:read',
  },
  {
    key: 'system.menu',
    type: SysMenuType.MENU,
    parentKey: 'system',
    name: '菜单管理',
    path: '/system/menu',
    component: '/system/menu',
    permission: 'system:menu',
    icon: 'ant-design:appstore-filled',
    orderNo: 20,
  },
  {
    key: 'system.menu.create',
    type: SysMenuType.PERMISSION,
    parentKey: 'system.menu',
    name: '菜单管理-新增',
    permission: 'system:menu:create',
  },
  {
    key: 'system.menu.delete',
    type: SysMenuType.PERMISSION,
    parentKey: 'system.menu',
    name: '菜单管理-删除',
    permission: 'system:menu:delete',
  },
  {
    key: 'system.menu.update',
    type: SysMenuType.PERMISSION,
    parentKey: 'system.menu',
    name: '菜单管理-修改',
    permission: 'system:menu:update',
  },
  {
    key: 'system.menu.read',
    type: SysMenuType.PERMISSION,
    parentKey: 'system.menu',
    name: '菜单管理-查询',
    permission: 'system:menu:read',
  },
  {
    key: 'system.params',
    type: SysMenuType.MENU,
    parentKey: 'system',
    name: '系统参数',
    path: '/system/params',
    component: '/system/params',
    permission: 'system:params',
    icon: 'ant-design:file-word-outlined',
    orderNo: 10,
  },
  {
    key: 'system.params.create',
    type: SysMenuType.PERMISSION,
    parentKey: 'system.params',
    name: '系统参数-新增',
    permission: 'system:params:create',
  },
  {
    key: 'system.params.update',
    type: SysMenuType.PERMISSION,
    parentKey: 'system.params',
    name: '系统参数-更新',
    permission: 'system:params:update',
  },
  {
    key: 'system.params.delete',
    type: SysMenuType.PERMISSION,
    parentKey: 'system.params',
    name: '系统参数-删除',
    permission: 'system:params:delete',
  },
  {
    key: 'system.params.read',
    type: SysMenuType.PERMISSION,
    parentKey: 'system.params',
    name: '系统参数-查询',
    permission: 'system:params:read',
  },
  {
    key: 'system.static',
    type: SysMenuType.PERMISSION,
    parentKey: 'system',
    name: '静态文件-查询',
    permission: 'system:static:read',
  },
  {
    key: 'system.static.uploadImage',
    type: SysMenuType.PERMISSION,
    parentKey: 'system',
    name: '静态文件-上传图片',
    permission: 'system:static:upload_image',
  },
  {
    key: 'system.static.delete',
    type: SysMenuType.PERMISSION,
    parentKey: 'system',
    name: '静态文件-删除',
    permission: 'system:static:delete',
  },
  {
    key: 'system.storage',
    type: SysMenuType.MENU,
    parentKey: 'system',
    name: '对象存储',
    path: '/system/storage',
    component: '/system/storage',
    permission: 'system:storage',
    icon: 'ant-design:cloud-server-outlined',
    orderNo: 5,
  },
  ...[
    ['read', '查询'],
    ['create', '新增'],
    ['update', '修改'],
    ['delete', '删除'],
    ['test', '连接测试'],
    ['bind', '用途绑定'],
  ].map(([action, name]) => ({
    key: `system.storage.${action}`,
    type: SysMenuType.PERMISSION,
    parentKey: 'system.storage',
    name: `对象存储-${name}`,
    permission: `system:storage:${action}`,
  })),
  {
    key: 'system.ai',
    type: SysMenuType.MENU,
    parentKey: 'system',
    name: 'AI 能力中心',
    path: '/system/ai',
    component: '/system/ai',
    permission: 'system:ai',
    icon: 'lucide:brain-circuit',
    orderNo: 4,
  },
  ...[
    ['read', '查询'],
    ['create', '新增'],
    ['update', '修改'],
    ['delete', '删除'],
    ['test', '连接测试'],
  ].map(([action, name]) => ({
    key: `system.ai.${action}`,
    type: SysMenuType.PERMISSION,
    parentKey: 'system.ai',
    name: `AI 能力中心-${name}`,
    permission: `system:ai:${action}`,
  })),
  {
    key: 'system.tutorial',
    type: SysMenuType.MENU,
    parentKey: 'system',
    name: '教程中心',
    path: '/system/tutorials',
    component: '/system/tutorials',
    permission: 'system:tutorial',
    icon: 'lucide:book-open-text',
    orderNo: 3,
  },
  ...[
    ['read', '查询'],
    ['create', '创建'],
    ['update', '编辑'],
    ['delete', '删除'],
    ['publish', '发布'],
    ['upload', '图片上传'],
  ].map(([action, name]) => ({
    key: `system.tutorial.${action}`,
    type: SysMenuType.PERMISSION,
    parentKey: 'system.tutorial',
    name: `教程${name}`,
    permission: `system:tutorial:${action}`,
  })),
  {
    key: 'monitor',
    type: SysMenuType.FOLDER,
    name: '系统监控',
    path: '/monitor',
    permission: 'monitor',
    icon: 'ep:monitor',
    orderNo: 980,
  },
  {
    key: 'monitor.task',
    type: SysMenuType.MENU,
    parentKey: 'monitor',
    name: '任务管理',
    path: '/monitor/task',
    component: '/monitor/task',
    permission: 'monitor:task',
    icon: 'ant-design:carry-out-twotone',
    orderNo: 40,
  },
  {
    key: 'monitor.task.create',
    type: SysMenuType.PERMISSION,
    parentKey: 'monitor.task',
    name: '任务管理-新增',
    permission: 'monitor:task:create',
  },
  {
    key: 'monitor.task.update',
    type: SysMenuType.PERMISSION,
    parentKey: 'monitor.task',
    name: '任务管理-更新',
    permission: 'monitor:task:update',
  },
  {
    key: 'monitor.task.read',
    type: SysMenuType.PERMISSION,
    parentKey: 'monitor.task',
    name: '任务管理-查询',
    permission: 'monitor:task:read',
  },
  {
    key: 'monitor.task.delete',
    type: SysMenuType.PERMISSION,
    parentKey: 'monitor.task',
    name: '任务管理-删除',
    permission: 'monitor:task:delete',
  },
  {
    key: 'monitor.task.once',
    type: SysMenuType.PERMISSION,
    parentKey: 'monitor.task',
    name: '任务管理-立即执行一次',
    permission: 'monitor:task:once',
  },
  {
    key: 'monitor.task.start',
    type: SysMenuType.PERMISSION,
    parentKey: 'monitor.task',
    name: '任务管理-启动',
    permission: 'monitor:task:start',
  },
  {
    key: 'monitor.task.stop',
    type: SysMenuType.PERMISSION,
    parentKey: 'monitor.task',
    name: '任务管理-停止',
    permission: 'monitor:task:stop',
  },
  {
    key: 'monitor.taskLog',
    type: SysMenuType.MENU,
    parentKey: 'monitor',
    name: '任务日志',
    path: '/monitor/task-log',
    component: '/monitor/task-log',
    permission: 'monitor:taskLog',
    icon: 'ant-design:bell-twotone',
    orderNo: 30,
    keepAlive: disabled,
  },
  {
    key: 'monitor.taskLog.read',
    type: SysMenuType.PERMISSION,
    parentKey: 'monitor.taskLog',
    name: '任务日志-查询',
    permission: 'monitor:taskLog:read',
  },
  {
    key: 'monitor.log',
    type: SysMenuType.MENU,
    parentKey: 'monitor',
    name: '系统日志',
    path: '/monitor/log',
    component: '/monitor/log',
    permission: 'monitor:log',
    icon: 'ep:operation',
    orderNo: 20,
  },
  {
    key: 'monitor.clientError',
    type: SysMenuType.MENU,
    parentKey: 'monitor',
    name: '客户端错误',
    path: '/monitor/client-error',
    component: '/monitor/client-error',
    permission: 'monitor:clientError',
    icon: 'lucide:bug',
    orderNo: 25,
  },
  {
    key: 'monitor.clientError.read',
    type: SysMenuType.PERMISSION,
    parentKey: 'monitor.clientError',
    name: '客户端错误-查询',
    permission: 'monitor:clientError:read',
  },
  {
    key: 'monitor.aiCallLog',
    type: SysMenuType.MENU,
    parentKey: 'monitor',
    name: 'AI 调用日志',
    path: '/monitor/ai-call-log',
    component: '/monitor/ai-call-log',
    permission: 'monitor:aiCallLog',
    icon: 'lucide:brain-circuit',
    orderNo: 24,
  },
  {
    key: 'monitor.aiCallLog.read',
    type: SysMenuType.PERMISSION,
    parentKey: 'monitor.aiCallLog',
    name: 'AI 调用日志-查询',
    permission: 'monitor:aiCallLog:read',
  },
  {
    key: 'monitor.clientError.delete',
    type: SysMenuType.PERMISSION,
    parentKey: 'monitor.clientError',
    name: '客户端错误-删除',
    permission: 'monitor:clientError:delete',
  },
  {
    key: 'monitor.log.read',
    type: SysMenuType.PERMISSION,
    parentKey: 'monitor.log',
    name: '系统日志-查询',
    permission: 'monitor:log:read',
  },
  {
    key: 'monitor.log.delete',
    type: SysMenuType.PERMISSION,
    parentKey: 'monitor.log',
    name: '系统日志-删除',
    permission: 'monitor:log:delete',
  },
  {
    key: 'monitor.tokenSession',
    type: SysMenuType.MENU,
    parentKey: 'monitor',
    name: 'Token 会话',
    path: '/monitor/online',
    component: '/monitor/online',
    permission: 'monitor:tokenSession',
    icon: 'ant-design:safety-certificate-outlined',
    orderNo: 10,
  },
  {
    key: 'monitor.tokenSession.read',
    type: SysMenuType.PERMISSION,
    parentKey: 'monitor.tokenSession',
    name: 'Token 会话-查询',
    permission: 'monitor:online:read',
  },
  {
    key: 'monitor.tokenSession.delete',
    type: SysMenuType.PERMISSION,
    parentKey: 'monitor.tokenSession',
    name: 'Token 会话-撤销',
    permission: 'monitor:online:delete',
  },
  {
    key: 'account',
    type: SysMenuType.FOLDER,
    name: '个人中心',
    path: '/profile',
    permission: 'sys:account',
    status: disabled,
    show: disabled,
    orderNo: 10,
  },
  {
    key: 'account.avatar',
    type: SysMenuType.PERMISSION,
    parentKey: 'account',
    name: '个人中心-上传头像',
    permission: 'sys:account:avatar',
  },
  {
    key: 'account.update',
    type: SysMenuType.PERMISSION,
    parentKey: 'account',
    name: '个人中心-更新资料',
    permission: 'sys:account:update',
  },
  {
    key: 'account.auth.enabledOtp',
    type: SysMenuType.PERMISSION,
    parentKey: 'account',
    name: '个人中心-绑定 OTP',
    permission: 'sys:auth:enabled_otp',
  },
  {
    key: 'account.auth.disabledOtp',
    type: SysMenuType.PERMISSION,
    parentKey: 'account',
    name: '个人中心-解绑 OTP',
    permission: 'sys:auth:disabled_otp',
  },
  {
    key: 'account.auth.modifyPwd',
    type: SysMenuType.PERMISSION,
    parentKey: 'account',
    name: '个人中心-修改密码',
    permission: 'sys:auth:modify_pwd',
  },
]
